name: icareindia
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_sound: ^9.6.0
  flutter_sound_record: ^3.3.2
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_nav_bar: ^5.0.6
  http: ^1.2.2
  intl: ^0.20.1
  just_audio: ^0.9.42
  line_icons: ^2.0.3
  lottie: ^3.1.3
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  razorpay_flutter: ^1.3.7
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Urbanist/Urbanist-VariableFont_wght.ttf
